/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxProvider */

#ifndef _Included_LinuxProvider
#define _Included_LinuxProvider
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     LinuxProvider
 * Method:    getKeyringPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_equinox_internal_security_linux_LinuxProvider_getKeyringPassword
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     LinuxProvider
 * Method:    setKeyringPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_equinox_internal_security_linux_LinuxProvider_setKeyringPassword
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
